Repository spryker-eco/new-relic, pull requests merged in 2020-07, with the labels that each got.

#7 TE-6867 /all console commands return exit code 0
  composer.json
  src/SprykerEco/Shared/NewRelic/NewRelicEnv.php
  tests/SprykerEcoTest/Service/NewRelic/_support/SprykerEcoPluginTester.php
Labels: merge-only

#8 Fix phpstan and CS and license.
  .travis.yml
  composer.json
  phpstan.neon
Labels: merge-only, ready-for-release

#9 TE-6867: License file header update
  LICENSE
Labels: merge-only, ready-for-release

#10 TE-6867: Fixed composer.json issues.
  composer.json
Labels: bug, merge-only
